---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test

notifications:
  email: false
  slack:
    secure: "W0hcWurt/REiYUqdld5FIfy/OQumaaZox3HIyrEoY37c8BUvG+LcdMvfcYbnkqXCbRqW42wO/cMqHRAeG0/jjNUvrwIgwbzykdbP0LQjcDKLIbWS2wtBqT4hATAzGkGqaHwyx+fMm5HMsnyoRPH/9p47arcHS+NQNPgg0uTRqI328HPOl5YaTZphTKO4k9SNdxSdk/tgkv2GNzDMiSnpVKi247qpxBestLHFKkYlGDIKViBmRGX/iVKSEyA5vmJlicJsBdH1PcUwsPbKMK/bnkwCLqH8ovkfkv6FFWTLcCBcsYwpavTKRJvMI296gpWxBae2ZzWxa4EBofVBMRrtGfw9BjgjE8qvusLM2FmlzpXdmeVH4q4YISrAXx9kjIwzwZ8yeVqB/3gIIziN1PvBNuYWNON7tcfOwgrpOHdPLBgFzKkf8kziNUVdXLc2mfJxupnl4hHm8YlL92Up/CzFxeXLc9qR2w+ATvDP+KtBjyU0vBUMqwJuwv9GnpdiTVCKSTqu88T9OpECEBeY+mpg+2CyV4gM+G5lcwieEt+aLUe4VWpGX47lWoPhwEyzJAXImgH74P+8RaQlhfotm6pe3tXWF5wywSoIG0fWwWr5xoNcR3KPTljQMPa24B0Tir61u6IupmnHre7wFAkSJMKTzjJWMzC7fi8Bnsxox+01808="

deploy:
  provider: heroku
  api_key:
    secure: "BwFniDp9ZxD/QF93duW7IvfhrQmvDCdGomCKzf9ckng+gotoGdX0mzZzFmi3WlFgczYqgObjZOnJOhmXtYCAub8kESn1qxE7vRDLdQiuoVfP5P8lQBTN75xtFkY3B8RPFwuWOJgroTXtDN6wdn0Z8eZkxaskCVzWw6dtfJ2PKECeDECiS3rEPdsCqFxw+PJIHHZCFsD3hPb4NdH/iReNdJ2lVX+k06byhJpiCYRcljcL8zzkpm2XJoY+0IOPlMz2p/uL3GTpjp5TjeVZtqdk59odEzuluq3+IqVVP3/CyiMPbD0JQ+ywy1wWjewRsKlJaYeQxlWpwmXZTlRlvhnolEJ68V3+WOjHUJuV4RGpDvD/ENpsKQqXHA+/FVdkYI5zGY9tEIq0n1qnllbex2xgba9wyebUjsvQ4KAopvjHB6JIeAqYN9+7HFfiLWTxUMHt0T591svKBGHgLYJUT1Ck8hS7VFXA6VtvVM9pie0Q+cN0OEQ20Hv/ZJoiOoDAbRd20ijyWAu2l+qA4F81FFQHUB3NXQL6A16fBegctGdhd/FQ1naooIOYA+0aGiXCIHlM/Ce0gwW++q4PqHTxhK+DiqTZLTMDkQ5rKp6wK4+v9nl4hYQxB6HRVd623rB9qPQWu1sWcEtO6T8aF2HnodeFmTSurCtXPbWZyEvFtkfo/qM="
  app: ember-ancestry
  on:
    tags: true
    repo: tomasbasham/ember-ancestry
