---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test

notifications:
  email: false
  slack:
    secure: "W0hcWurt/REiYUqdld5FIfy/OQumaaZox3HIyrEoY37c8BUvG+LcdMvfcYbnkqXCbRqW42wO/cMqHRAeG0/jjNUvrwIgwbzykdbP0LQjcDKLIbWS2wtBqT4hATAzGkGqaHwyx+fMm5HMsnyoRPH/9p47arcHS+NQNPgg0uTRqI328HPOl5YaTZphTKO4k9SNdxSdk/tgkv2GNzDMiSnpVKi247qpxBestLHFKkYlGDIKViBmRGX/iVKSEyA5vmJlicJsBdH1PcUwsPbKMK/bnkwCLqH8ovkfkv6FFWTLcCBcsYwpavTKRJvMI296gpWxBae2ZzWxa4EBofVBMRrtGfw9BjgjE8qvusLM2FmlzpXdmeVH4q4YISrAXx9kjIwzwZ8yeVqB/3gIIziN1PvBNuYWNON7tcfOwgrpOHdPLBgFzKkf8kziNUVdXLc2mfJxupnl4hHm8YlL92Up/CzFxeXLc9qR2w+ATvDP+KtBjyU0vBUMqwJuwv9GnpdiTVCKSTqu88T9OpECEBeY+mpg+2CyV4gM+G5lcwieEt+aLUe4VWpGX47lWoPhwEyzJAXImgH74P+8RaQlhfotm6pe3tXWF5wywSoIG0fWwWr5xoNcR3KPTljQMPa24B0Tir61u6IupmnHre7wFAkSJMKTzjJWMzC7fi8Bnsxox+01808="
