include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-sitemap
  - jemoji

# Site settings
title: ember-ancestry
description: An ember-cli family tree visualisation application
lang: en_GB
url: https://ember-ancestry.com

# Build settings
markdown: kramdown
highlighter: rouge
